---
title: "Visualization"
author: "Xavier"
date: "April 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
data = read.csv('housing_price.csv')
library('VIM') # Missing value
```









```{r}

getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

data$KITCHENS[is.na(data$KITCHENS)] <- getmode(data$KITCHENS[!is.na(data$KITCHENS)])



med_diff_built_remodel <-floor(median(data$YR_RMDL[!is.na(data$YR_RMDL)&!is.na(data$AYB)]- 
                                data$AYB[!is.na(data$YR_RMDL)&!is.na(data$AYB)] ))


# Fill AYB and YR_RMDL
data$YR_RMDL[is.na(data$YR_RMDL)&!is.na(data$AYB)] <-data$AYB[is.na(data$YR_RMDL)&!is.na(data$AYB)]


#Missing Both
missing_both <- is.na(data$YR_RMDL)&is.na(data$AYB)

data$AYB[missing_both]<-floor(median(data$AYB[!is.na(data$AYB)]))

data$YR_RMDL[missing_both]<-data$AYB[missing_both]- med_diff_built_remodel


missing_built_have_remodel <- (!is.na(data$YR_RMDL)&is.na(data$AYB))
data$AYB[missing_built_have_remodel] <- data$YR_RMDL[missing_built_have_remodel]-med_diff_built_remodel

data$STORIES[is.na(data$STORIES)]<-floor(median(data$STORIES[!is.na(data$STORIES)]))
```


##Outliers / Extreme value

By eyeball the data, we can see there is several outliers
```{r}
data[data$YR_RMDL==20,]
data$YR_RMDL[data$YR_RMDL==20]=data$AYB[data$YR_RMDL==20]+med_diff_built_remodel
data$AC[data$AC ==0] <- getmode(data$AC[data$AC !=0])
```

```{r}
data$STORIES[data$STORIES>=14] <- floor(median(data$STORIES[data$STORIES<14]))
```
The height of buildings in Washington is limited by the Height of Buildings Act.  	Tallest residential building in Washington, D.C. Tallest building completed in the city in the 2000s has 14 floors

```{r}
#write.csv(data,'../data/pre_data.csv')
```

##Encode

```{r}
data$AC <- factor(data$AC,level=c('Y','N'), label=c(1,0))

data$GRADE <- as.numeric(factor(data$GRADE,level=c('Low Quality', 'Fair Quality', 'Average', 'Above Average', 'Good Quality', 'Very Good', 'Excellent', 'Superior', 'Exceptional-A', 'Exceptional-B', 'Exceptional-C', 'Exceptional-D', ordered= TRUE)))

data$CNDTN <- as.numeric(factor(data$CNDTN,level=c('Poor', 'Fair', 'Average', 'Good', 'Very Good','Excellent', ordered= TRUE)))



data$NATIONALGRID <- as.numeric(data$NATIONALGRID)

data$ASSESSMENT_NBHD <- as.factor(data$ASSESSMENT_NBHD)

data$STYLE <- as.numeric(data$STYLE)

#HEAT
#data$STRUCT <- as.numeric(data$STRUCT)

#data$EXTWALL <- as.numeric(data$EXTWALL)
#data$INTWALL <- as.numeric(data$INTWALL)
#data$ROOF <- as.numeric(data$ROOF)
#data$WARD <- as.numeric(data$WARD)
#data$QUADRANT <- as.numeric(data$QUADRANT)



data$HEAT <- as.character(data$HEAT)
data$HEAT[data$HEAT=='Air-oil'|
                data$HEAT=='Electric Rad'|
                 data$HEAT=='Evp Cool'|
                 data$HEAT=='Gravity Furnac'|
                 data$HEAT=='Ind Unit'|
                 data$HEAT=='No Data'|
                 data$HEAT=='Wall Furnace'
                 ] <- sample(data$HEAT[data$HEAT!='Air-oil'& data$HEAT=='Electric Rad' & data$HEAT!='Evp Cool'&
                 data$HEAT!='Gravity Furnac'&
                 data$HEAT!='Ind Unit'&
                 data$HEAT!='No Data'&
                 data$HEAT!='Wall Furnace'
                 ],size = 8)
data$HEAT<-as.factor(data$HEAT)


#EXTWALL
#data$EXTWALL[data$EXTWALL == 'Adobe'| data$EXTWALL == 'Default'| data$EXTWALL == 'Plywood' ] <- sample((data$EXTWALL[data$EXTWALL != 'Adobe'& data$EXTWALL != 'Default'& data$EXTWALL != 'Plywood' ]),size = 8)
#data$EXTWALL<-as.factor(data$EXTWALL)



data$QUADRANT[data$QUADRANT == ""] <- sample(data$QUADRANT[data$QUADRANT != ""],size = 65)

#data$INTWALL[data$INTWALL == 'Vinyl Comp'] <- 'Carpet'
```



```{r}
library(gbm)
library(mgcv)

# year rebuild
data$SALEYEAR <- as.numeric(substr(data$SALEDATE,0,4))
data$SALEMONTH <- as.numeric(substr(data$SALEDATE,6,7))
data$SALEDATE <- as.numeric(data$SALEDATE)

RMLSE_Score <- function(real,pred, take_log = TRUE){
  if (take_log){
    print(sqrt(1/length(real)* sum( (log(real) -log(pred))^2 ,na.rm=TRUE )))
  }else{
    print(sqrt(1/length(real)* sum( (real -pred)^2 ,na.rm=TRUE )))
  }
  
}
```

```{r}


#foul_num <- 1
xg_at1 <- function(fold_num){
  train<-data[data$fold !=fold_num,]
  train <- subset(train, select= - c(Id,fold, ASSESSMENT_SUBNBHD,FULLADDRESS))
  train$PRICE = log(train$PRICE)
    gam.object <- gam(PRICE~ s(BATHRM)+ HF_BATHRM + I(HF_BATHRM^2) + AC + s(ROOMS) + s(BEDRM)+ s(AYB)  + s(YR_RMDL)+ s(EYB) + s(SALEDATE) + s(GBA) + CNDTN  + KITCHENS + s(LANDAREA) + te(LANDAREA, LONGITUDE,by =CNDTN)+ s(FIREPLACES) + s(ZIPCODE) + te(SALEDATE, ZIPCODE)+ te(SALEDATE, CENSUS_TRACT) + te(ZIPCODE,LATITUDE,LONGITUDE) + CENSUS_TRACT + ASSESSMENT_NBHD + s(LATITUDE)
                    + STRUCT 
                    + GRADE 
                    + WARD
                    + QUADRANT
                    + I(BEDRM^2)
                    , data=train)
  
  test<-data[data$fold ==fold_num,]
  
  test_price <- log(test$PRICE)
  
  
  test<-subset(test, select=-c(Id,fold, ASSESSMENT_SUBNBHD,FULLADDRESS))
  
  predict_price<-predict(gam.object,test)
  
  RMLSE_Score(test_price,predict_price, FALSE)
  return (cbind(data[data$fold==fold_num,]$Id,predict_price,test_price))
}

system.time(at1_1 <-xg_at1(1))

system.time(at1_2 <-xg_at1(2))
system.time(at1_3 <-xg_at1(3))
system.time(at1_4 <-xg_at1(4))
system.time(at1_5 <-xg_at1(5))

total<-data.frame(rbind(at1_1,at1_2,at1_3,at1_4,at1_5))
RMLSE_Score(total$test_price,total$predict_price, FALSE)


output <- data.frame(id = total$V1, PRICE = exp(total$predict_price))
write.csv(output, "pre_data_smoo.csv",row.names = FALSE)

```
